baseURL = 'https://work-bvs.github.io/'
defaultContentLanguage = "ru"
languageCode = 'ru-ru'
title = ''
theme = 'gallery'
copyright = "© 1996-2025 | версия 4.0"

disableKinds = ['taxonomy', 'term']
enableRobotsTXT = false
timeZone = "Europe/Moscow"
timeout = "120s"